version: 0.2
phases:
  install:
    commands:
      - echo 'Installing Terraform'
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version
      - echo {
    "UserId": "AIDAQSQRW75X7XTKCDJHW",
    "Account": "039765606255",
    "Arn": "arn:aws:iam::039765606255:user/sky_ndoh"
}
  build:
    commands:
      - cd pre-req-resources
      - terraform init
      - terraform apply -auto-approve
